### ISSUE TITLE
Issues in braindecode recently introduced by skorch

### ISSUE THREAD

**Issue by BenjaminBossan** [skorch-dev/skorch#1016]
Copying from [this comment](https://github.com/skorch-dev/skorch/pull/1004#issuecomment-1699602464):

> So sorry for the delay. I started to make a little code to show the difference, but I realized that there is something more structural that changed in skorch that affected the braindecode. Some update affected everything when we created an environment from scratch. It was a structural thing that even changed learning behaviour. I'm still working on isolating the root; I hope to finish by Friday.
> Well, from the beginning, at braindecode, we had a philosophy that we would always use the most up-to-date versions of the libraries we depend on. This was integrated into our CI; we were using skorch directly from Git Hub.
> The first error we got was that almost all acceptance tests broke (https://github.com/braindecode/braindecode/pull/461). In acceptance tests, we basically trained on a toy dataset for 10 epochs and compared the results with historical data. I fixed this by updating the tests since it didn't look serious. At first, I thought it was some change related to version 0.14.
> Preventively, we limited the skorch on the CI to try to resolve it, and it seemed to have resolved it. However, now, when we install braindecode with sub-dependency skorch, everything breaks. I'll show you in CI here: https://github.com/braindecode/braindecode/pull/471

**Comment by bruAristimunha** [comment]
Hi @BenjaminBossan!

Thank you very much for opening this issue. I followed his recommendation, and it was unclear why we now need the `classes` parameter when we tested in Python version 3.8 or higher. I tried to follow the instructions and create a mini-code to deliver to you; however, as we are going to make a code sprint next week, I preferred to incorporate this new parameter into the examples in the braindecode rather than finding out exactly what generated this requirement.

From what I studied, it could even have been sklearn. The lesson has been learned, and we will improve the control of these dependecies. For me, we can close this issue, and I thank you for your immense work on skorch :)

**Comment by BenjaminBossan** [comment]
> From what I studied, it could even have been sklearn

This is very much possible. Actually, some skorch code also started failing because somewhere inside of sklearn, there was a change that suddenly required `classes_` when previously it was not required. See [this comment](https://github.com/skorch-dev/skorch/pull/990#issue-1782477859):

> It seems that the classes_ attribute is now required on classifiers for some stuff related to sklearn scoring, where previously it wasn't

I also tried to figure out the exact change but then gave up and just accepted it.

> I thank you for your immense work on skorch :)

Thanks a lot, always happy to hear it.
