### ISSUE TITLE
Python 2.7 compatibility??

### ISSUE THREAD

**Issue by ottonemo** [skorch-dev/skorch#115]

**Comment by ottonemo** [comment]
numpy drops support for 2.7. This settles it IMO

**Comment by benjamin-work** [comment]
2020

But yeah, let's only do it if lots of people complain.

**Comment by alexCamFRUS** [comment]
I would appreciate having a version compatible with python 2.7 . Thank you :)

**Comment by derenrich** [comment]
Ditto

**Comment by benjamin-work** [comment]
A question to those concerned: Do you need Python 2.7 for personal projects or because your company requires it?

**Comment by alexandreCameron** [comment]
Work projects

**Comment by manuelbaum** [comment]
I would also need it for work projects. would be really helpful!

**Comment by benjamin-work** [comment]
I had a look at the code and the changes needed to make skorch work with Python 2.7 (not even talking about making it functionally the same) is non-trivial. The number of people who need it does not appear to be big enough to justify the time investment (especially since Python 2 support will drop soon).

I will still leave this open in case more people want Python 2 support.

**Comment by AlexLuya** [comment]
need it too

**Comment by ottonemo** [comment]
Hey! It's 2020 now. Python 2.7 is nearly dead for relevant packages such as numpy ([source](https://numpy.org/neps/nep-0014-dropping-python2.7-proposal.html)). We won't support Python 2.7.

Opting for closing this.

**Comment by alexandreCameron** [comment]
You can officially annonce not to support Python 2.7. Two years after the first post, we can confirm that we weren't enough users to make the dev. In my case, I coded a custom function for the project.

You probably still have people with python 2.7 code for a few years...

> Python
> 
> By default, macOS is installed with Python 2.7. PyTorch can be installed with Python 2.7, but it is recommended that you use Python 3.6 or greater, which can be installed either through the Anaconda package manager (see below), Homebrew, or the Python website.

From https://pytorch.org/get-started/locally/

**Comment by BenjaminBossan** [comment]
@alexandreCameron 

You are right, for a few years, there will still be people who for some reason or another, have to work with Python 2.7. If you'd like to, you could share your custom function, maybe it helps those people.

As there wasn't really a critical mass in support of Python 2.7 and since it's end of life is now well known, I will close the issue (people can still post helpful snippets here).
