### ISSUE TITLE
Folder examples/datasets is misleading

### ISSUE THREAD

**Issue by githubnemo** [skorch-dev/skorch#423]
Someone might expect dataset examples whereas this folder is just a place to store temporary datasets. This should probably be renamed or removed and created on the fly.

**Comment by thomasjpfan** [comment]
For reference, it looks like only `examples/benchmarks/mnist.py` uses this folder.

**Comment by BenjaminBossan** [comment]
The idea was to have a single folder that contains all the data used in all the examples, instead of having data lying around everywhere. But this was never enforced. If there is no standard, we could as well get rid of the folder. 

On the other hand, since only one example is affected, renaming should be easy. Then we can slowly transition the other examples.

**Comment by BenjaminBossan** [comment]
In case we're working on this, `fetch_mldata` is currently broken. [Here](https://gist.github.com/BenjaminBossan/a2d12b0ade84c53a3e68091c333dc803) is a workaround to get [mnist.py](https://github.com/dnouri/skorch/blob/master/examples/benchmarks/mnist.py) working, but this is probably not a permanent solution.

**Comment by thomasjpfan** [comment]
scikit-learn has deprecated `fetch_mldata`. We can use `fetch_openml` to get the same mnist dataset.
