### ISSUE TITLE
Linear classifier with 301 features, 80 samples, 8 classes using skorch is 37 times slower 

### ISSUE THREAD

**Issue by philip-bl** [skorch-dev/skorch#433]
I needed to learn pytorch so I decided to start with simple models. I like helper functions of sklearn so I installed skorch. And on my first try skorch made training 37 times slower!!!

* Self sufficient [example](https://gist.github.com/philip-bl/35be85525e06d8c3cf47a676f9a9497e) reproducing the problem on my computer.
* [Installation info](https://gist.github.com/philip-bl/8a7ec08a281e9212ff427043c7b26a9c)

**Comment by BenjaminBossan** [comment]
Thanks for reporting.

skorch introduces a fixed overhead because it does more things than pure pytorch. We found the overhead to typically be negligible for any realistic kind of task (e.g. [here](https://github.com/dnouri/skorch/blob/master/examples/benchmarks/mnist.py)), where most time is spent on the forward and backward pass. Your task has a very small dataset and a lot of iterations, which magnifies the skorch overhead. If you discover a severe performance overhead using a realistic dataset, please let us know.

**Comment by ottonemo** [comment]
@philip-bl did this answer your question?

**Comment by philip-bl** [comment]
@ottonemo Not really.

I figured out that I can reduct it from 37 times to 2 times slower by disabling all callbacks.

Also I suspect that additional execution time per epoch increases if I increase `max_epochs` parameter, because for smaller values I think overhead multiplier was much less than 37.

And I suspect that overhead can be decreased significantly, because additional 2 minutes for just 5000 cycles seems too much.

**Comment by BenjaminBossan** [comment]
@philip-bl Anything more to add to this? Otherwise I'll close this issue in a couple of days.
