### ISSUE TITLE
Batch Normalization with Batch Size of 1

### ISSUE THREAD

**Issue by ZaydH** [skorch-dev/skorch#477]
Batch normalization (e.g., `BatchNorm1d`) cannot support batch sizes of 1.  When using the `fit` command, you can run into the batch size of 1 problem.  When it occurs with batch norm, an error like the one below occurs.

`ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 64])`

It would be nice if there was a way we could specifically disable batches of size 1.  Perhaps it could be an optional feature where a batch of size one is skipped or joined to a previous batch.   It may already be supported and I do not know it.

Here is a gist where I got the issue with:

https://gist.github.com/ZaydH/ba4685d1b49563bc8d76c7ee6f45cef5

* `torch`: 1.1.0
* `skorch`: 0.5.0.post0
* Python: 3.7.1

**Comment by BenjaminBossan** [comment]
As a quick fix, PyTorch offers the option to drop the last batch if it's incomplete. To pass this option via skorch, use:

`net = NeuralNet(..., iterator_train__drop_last=True, iterator_valid__drop_last=True)`

Of course, this is not an ideal situation. But since we delegate sampling to PyTorch, I don't think there should be a skorch-specific solution; the solution needs to be delegated to PyTorch.

It appears that the way to go is PyTorch's [`BatchSampler`](https://pytorch.org/docs/stable/data.html#torch.utils.data.BatchSampler). If you implement a sampler with the option to drop batches of size 1, I could see it being included in `skorch.helper`. It may even be worth including in PyTorch itself.

**Comment by ZaydH** [comment]
Thanks @BenjaminBossan.  These are good ideas.  I verified they basically worked in the simple test case I provided.  

I did run into an issue when there is only a single validation batch.  The error message you get (see below) is perhaps a bit cryptic.

`TypeError: __call__() missing 1 required positional argument: 'y_true'`

When I tried to use technique with `sklearn`'s `CalibratedClassifierCV`, I get the runtime error below.  It seems since batch data is missing, the `sklearn`'s self checks fail. 

```
Traceback (most recent call last):
  ...
  File "XXXXX.py", line 264, in fit
    self._g.fit(merged_x, merged_y)
  File "<python 3.7.1>/sklearn/calibration.py", line 196, in fit
    calibrated_classifier.fit(X[test], y[test])
  File "<python 3.7.1>/sklearn/calibration.py", line 356, in fit
    calibrator.fit(this_df, Y[:, k], sample_weight)
  File "<python 3.7.1>/sklearn/isotonic.py", line 323, in fit
    X, y = self._build_y(X, y, sample_weight)
  File "<python 3.7.1>/sklearn/isotonic.py", line 242, in _build_y
    check_consistent_length(X, y, sample_weight)
  File "<python 3.7.1>/sklearn/utils/validation.py", line 235, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [832, 891]

```

Is this a salvageable error?  If you need an MWE, I can try to construct one.

**Comment by BenjaminBossan** [comment]
So I'm not quite sure how the two errors you reported are related. Did you solve the first only to get to the second?

Regarding the sklearn error, I suspect that because values are dropped, the number of predictions is not equal to the number of inputs or targets. I don't see an easy solution to that. On the one hand, you could try to avoid having batches dropped by choosing a sufficiently large batch size, so that a batch of 1 just does not happen (though I guess you would have already done so if possible). Or you could restrict your training data size to be a multiple of the batch size.

On the other hand, you could try to fiddle with sklearn to prune arrays that are too long because of the dropped batches by digging into the code and overriding the corresponding methods.

**Comment by BenjaminBossan** [comment]
@ZaydH Any updates?

**Comment by kacper1095** [comment]
@ZaydH The first problem is that you instantiated `Module` class inside the constructor. However, the class should be passed by name to the `NeuralNet` or `NeuralNetClassifier`. So, line 26:
```python
mod = NeuralNetClassifier(Module(), batch_size=bs)
```
should be changed to
```python
mod = NeuralNetClassifier(Module, batch_size=bs)
```
Or are there any advantages of instantiating module inside the constructor, that I don't know?

**Comment by ZaydH** [comment]
@BenjaminBossan My apologies for dragging on this.  I had some end of the term projects that forced me to sideline this for a time.  I will get back to this at the end of next week.

**Comment by BenjaminBossan** [comment]
No worries :)

**Comment by ZaydH** [comment]
@kacper1095 I looked into what you referenced.  My reading of the `skorch` source is that the `module` parameter can be either a `Callable` or a `torch.nn.module`.  When the `fit` method is initially called, `skorch` runs an initializer function `[initialize_module](https://github.com/skorch-dev/skorch/blob/51000d1e6f33e486d4586f91fd321e5e13c15ad3/skorch/net.py#L458)`.  

This function checks if `module` is already a `nn.Module` object and if not initializes it.

I did verify that I can get the error even if I let `skorch` initialize `module`.

**Comment by BenjaminBossan** [comment]
So first let me confirm that it is possible (though not recommended) to pass an initialized module, so that should not be the problem. Coming back to the issue at hand, let me try to summarize what the problem is:

For one reason or another, it is desired to drop some batches from the training and validation data. However, when `predict(_proba)` is called, this leads to a lower number of predictions. When sklearn checks the length of the prediction and the length of the target, it notices the inconsistency and raises an error. Is that the correct state?

If this is indeed the problem, here are some proposals to solve it:

* Try to avoid dropping batches (see discussion above)
* If you have `n` samples and you know in advance that `m` samples will be dropped, pass only `n-m` samples to the scoring function. E.g.: `accuracy(net, X[:n-m], y[:n-m])`. This approach should hopefully fix the example using `CalibratedClassifierCV`.
* If you encounter the error during scoring: Write your own scoring function that automatically truncates the data:

```python
# assume we want to measure accuracy
from sklearn.metrics import accuracy_score
def my_accuracy(estimator, X, y):
    y_pred = estimator.predict(X)
    n = len(y_pred)
    y = y[:n]
    return accuracy_score(y, y_pred)
```

Both of these solutions are not particularly satisfying, but I currently see no other way.

**Comment by ottonemo** [comment]
Is this issue still open? Has your question been answered? Do you still have questions?

**Comment by ZaydH** [comment]
This can be closed.  Sorry for leaving it open.
