### ISSUE TITLE
NeuralNetClassifier does not take Dataset as input?

### ISSUE THREAD

**Issue by ThyrixYang** [skorch-dev/skorch#547]
Hi,
I can train a NeuralNet with Dataset as input, but when I change to NeuralNetClassifier, it said that y is missing.
So NeuralNetClassifier does not support Dataset input?

**Comment by BenjaminBossan** [comment]
The main reason why `NeuralNetClassifier` wants to have a `y` is because it tries to do a stratified split on the data, for which it requires `y`. If it's possible for you to extract your `y`, you can still use it:

```python
y = np.asarray([yi for _, yi in my_dataset])
net.fit(my_dataset, y)
```

If that doesn't work for you, you can still just use `NeuralNet` or you can change the cv split to not be stratified:

```python
from skorch.dataset import CVSplit
net = NeuralNetClassifier(..., train_split=CVSplit(5))
net.fit(my_dataset, y=None)
```

**Comment by ThyrixYang** [comment]
Thanks for reply
