### ISSUE TITLE
Deperecated check_is_fitted call

### ISSUE THREAD

**Issue by fradav** [skorch-dev/skorch#570]
When calling GridsearchCV I got :
```plain
/home/fradav/.conda/envs/pytorch/lib/python3.7/site-packages/scikit_learn-0.22rc3-py3.7-linux-x86_64.egg/sklearn/utils/validation.py:937: FutureWarning: Passing all_or_any to check_is_fitted is deprecated and will be removed in 0.23. The any_or_all argument is ignored.
```
This is with scikit-learn `0.22rc3` version.

Regards,

**Comment by thomasjpfan** [comment]
Can you provide a reproducible code example where the warning appears?

**Comment by BenjaminBossan** [comment]
We use sklearn's `check_is_fitted` with that parameter here:

https://github.com/skorch-dev/skorch/blob/7d275df28d49de782373174a0882bc8c31fda844/skorch/utils.py#L502

Since the parameter was deprecated [here](https://github.com/scikit-learn/scikit-learn/pull/145459), we should also remove it.

The question now is if we want to deprecate it as well or just flat out remove it. My guess is that nobody uses `skorch.utils.check_is_fitted` directly, which would make it safe for immediate removal. If we deprecate, people will see two deprecation warnings while just using normal skorch code, and they cannot even easily fix it.

**Comment by thomasjpfan** [comment]
It still has a use case in skorch by raising skorch specific exceptions. Since it is not being used, we can change its behavior without much consequences.

A quick fix would be to check the sklearn version and make sure to call `check_is_fitted` with the correct arguments (depending on version).

**Comment by BenjaminBossan** [comment]
I just saw that the changes to `check_is_fitted` make it unusable for use. E.g.:

```
    attributes : deprecated, ignored
        .. deprecated:: 0.22
           `attributes` is deprecated, is currently ignored and will be removed
           in 0.23.
```

Instead, the function now only checks if there are *any* attributes that end on `_`. This is the case for skorch even before fitting.

**Comment by fradav** [comment]
There is also : 
```plain
/data/miniconda3/envs/pytorch/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
```

Should I make a separate issue for this?

**Comment by BenjaminBossan** [comment]
Thanks for that. Yes, please open a new issue for that.

**Comment by BenjaminBossan** [comment]
@fradav This issue can be closed, right?

**Comment by ottonemo** [comment]
I think it can be closed. @fradav please re-open the issue if you object.
