### ISSUE TITLE
Ability to pass kwargs to predict

### ISSUE THREAD

**Issue by cgarciae** [skorch-dev/skorch#598]
This is probably beyond the `sklearn` API design but it would be really useful to be able to pass some keyword arguments to `predict` and friends such that they are forwarded to `nn.Module.forward`. 

My current use-case is that I have an auto-encoder model and in its `forward` method I have the keyword argument `return_embedding=False` which I would like to set to `True` during inference.

**Comment by cgarciae** [comment]
Looking at the codebase it seems that the `infer` method already supports this so it would just be a matter of passing a `**kwargs` variable around till it reaches it.

**Comment by BenjaminBossan** [comment]
As you guessed, having custom `kwargs` for predict is not really supported by sklearn, hence not by skorch. For the specific case you presented, maybe you could achieve the same goal by:

* having an attribute on your module called `return_embedding` (instead of having it as an argument)
* the module looks that value up on `self` and determines if it should return the embeddings or not
* when you need the embeddings, you set `net.module_.return_embeddings = True`

It's not super elegant, but might be enough. As to the question how to handle multiple outputs from the `forward` call, we have a section about that in the [docs](https://skorch.readthedocs.io/en/stable/user/FAQ.html#how-can-i-deal-with-multiple-return-values-from-forward).

Feel free to ask if you have any further questions, otherwise you can close the issue.

**Comment by cgarciae** [comment]
@BenjaminBossan I appreciate `skorch` remains true to the scikit-learn API :) I found it easier to manually call the forward method of the network's module:

```python
X = torch.tensor(X_test, device="cuda")
y_pred = net.module(X, return_embeddings=True)
```
Since it fit in memory, but I would probably use `return_embeddings` as a field otherwise.

**Comment by BenjaminBossan** [comment]
@cgarciae Great that you found a solution that works for you.

For any future readers: That is also possible and the memory problem that is mentioned concerns the fact that data is not batched. If you run into memory problems, use the solution posted above.

**Comment by tristankpka** [comment]
@BenjaminBossan I tried `net.module_.return_embeddings = True` but when calling `forward ` to compute a score during a callback but the value was not set to `True`. It is at the end of that first epoch but not during the callback.

Is it possible to modify module attributes during an epoch scoring callback ?

**Comment by BenjaminBossan** [comment]
Hey @tristankpka, would it be possible for you to show some code so that I understand your problem better?

> Is it possible to modify module attributes during an epoch scoring callback ?

Without knowing all the details: Yes, that should be possible. You probably have to remember the previous value and restore it after you're done to avoid any nasty side-effects.

**Comment by tristankpka** [comment]
Sure ! 

I have a scoring callback function that need to indicate to my CVAE that it needs to sample its latent space by a given number. I wrap into EpochScoring this func: 

```
def score_khi_test_MMGGMM(net, X, y):
    net.module_.n_samples = 100
    mu_decode_only, logvar_decode_only, _, _, _, _ = net.forward(X)
    net.module_.n_samples = 1
    return float(0)
```

In my model.py :
```
def forward(self, x, y):
    if self.n_samples > 1:
        print(self.n_samples)
```
It never prints that samples number.

However, if I remove `net.module_.n_samples = 1` I get the print but only when the second epoch is finished. Strangely the first one get a zero score but I don't have any print statement indicating that my attribute has been changed.

I hope it clears my problem, I find this behavior quite strange and rather difficult to explain... :)

**Comment by BenjaminBossan** [comment]
Honestly, I still don't quite understand what you want to achieve, for instance what `n_samples` does and why it needs to be 1 sometimes. What is its value initially, i.e. before `score_khi_test_MMGGMM` is called?

> It never prints that samples number.

Okay, this is surprising. I assume that the `forward` method you show is on the module, not the net. What happens if you print `self.n_samples` unconditionally (without the `if`)?

**Comment by tristankpka** [comment]
I apologise for being unclear and thank you for your time.
During training time I train my CVAE by sampling z (my latent variables) only once.
But at test time, during the epoch scoring, I want multiple samples of z, lets call them, z_i to get p(y|x, z_i).
At each epoch, I would like to train the network, switch the samples number during the callback and get back to training with one sample.
Initially, `n_samples ` is set to 1.

Correct, it's on the module. Without any condition, `n_samples=1` is printed.

**Comment by BenjaminBossan** [comment]
Okay, now I understand your intent. The reason why this doesn't work is that by default, skorch uses caching of the prediction. This is so that the same prediction is not computed multiple times for each scoring callback. To turn this off, use:

```python
net = NeuralNet(
    ...
    callbacks=[EpochScoring(score_khi_test_MMGGMM, use_caching=False, ...)],
)
```

For your use case, you might consider using the `training` attribute on the module to choose between the number of samples. This way, at training time, you can have a different value than at validation and inference time, without the need to set the attribute during scoring. It could look like this:

```python
class MyModule(nn.Module):
    def __init__(
            self,
            n_samples_train=1,
            n_samples_valid=100,
    ):
        ...

    def forward(self, X, ...):
        if self.training:
            n_samples = self.n_samples_train
        else:
            n_samples = self.n_samples_valid
        ...
```
