### ISSUE TITLE
EpochScoring/Attempting to save history raises TypeError:Object of type float32 or Tensor is not JSON serializable with custom metrics

### ISSUE THREAD

**Issue by truenicoco** [skorch-dev/skorch#629]
I am using a custom metrics with `EpochScoring`. Trying to save `net.history` throws this type of error.

I worked around this by passing a different function to `EpochScoring` that ensures it returns a native python float instead of a numpy or torch float, but I feel like `skorch` should transparently handle this. 

Not sure if this should be done in `net.save_params` or `EpochScoring` though. Maybe [here](https://github.com/skorch-dev/skorch/blob/0f186aea9da37a37860f1c447980d030c2506823/skorch/callbacks/scoring.py#L180)? I am not machine learning savvy enough to know all the cases this should handle. Maybe this should be handled in the JSON module of the standard lib, I don't know…

**Comment by BenjaminBossan** [comment]
Thanks for reporting. It's true that this is a bit of a trap. It's not really fixable in the scorer, since many things can write to the history. I think we could be doing this:

* better document on the net, on the history class and on `EpochScoring` that you should prefer json-serializable types
* when calling `save_params`, catch this error and report a better error message, with suggestions for mitigations

If you want to, you could work on these suggestions.

Note that we don't want to prevent writing non json-serializable data to history, since it's actually okay as long as you don't want to `save_params` the history, which I suspect most people don't do. That is because often you don't need to restore the history (e.g. because you only need the net for inference) or because you persist the whole not using pickle, which should work just fine. For those people, changing the current behavior could actually break their code.

**Comment by truenicoco** [comment]
Thanks for your answer. Instead of just catching the error and reporting a better error message, don't you think it would be OK to convert to a python float or int whenever the non serializable type is in fact a scalar in wrapped in a `torch.Tensor` or `nd.ndarray`?

Maybe it would even be OK to convert to a list when needed. Or even a list of lists (of lists…)… Both libraries functions provide dedicated to that last case: [`Tensor.tolist()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.tolist) and [`ndarray.tolist()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html#numpy.ndarray.tolist)

**Comment by BenjaminBossan** [comment]
> Instead of just catching the error and reporting a better error message, don't you think it would be OK to convert to a python float or int

I was thinking about this as well but I see a few problems there:

* it's only possible with a few types but anyone can store any kind of type in the history
* users might be wondering why after restoring the history, their types have changed

I think reporting a nice error message that mentions that types should be json-serializable or otherwise pickle needs to be used is more transparent and leads to cleaner code. It would be conceivable to add an option (opt in) to coerce the types, but that's a lot of work for only little benefit.

**Comment by BenjaminBossan** [comment]
I believe there is nothing further to discuss here, so I will close for now.
