### ISSUE TITLE
TypeError: cannot serialize '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by drr3d** [skorch-dev/skorch#654]
Hi There 

i try to replicate this: [translation.ipynb](https://github.com/skorch-dev/skorch/blob/master/examples/translation/translation.ipynb) into separate python file.

i dont run the `gs.fit(X, y)` just directly execute `trainer.fit(X, y)`

when i try to dump using pickle:
```
with open('translation', 'wb') as f:
    pickle.dump(trainer, f)
```

it throws: `TypeError: cannot serialize '_io.TextIOWrapper' object`

when i do some search, many says it because **multiprocessing**.

then i try to replicate using [mnist.ipynb](https://github.com/skorch-dev/skorch/blob/master/notebooks/MNIST.ipynb) by putting it on separate python file, there is no error.

i wonder what going wrong?

Cheers :beers:

**Comment by BenjaminBossan** [comment]
I don't think it has to do with multiprocessing. The reason why you find that when searching is that multiprocessing also pickles code under the hood. But in your case, you use pickle directly, causing the error.

For me, this looks like `trainer` holds a reference to a `TextIOWrapper` object, although I can't see where this should be coming from. Did you make any further modification to the script?

The only theoretical culprit I see is [here](https://github.com/skorch-dev/skorch/blob/c72e1fec496e3d80b9ca0709df556c07c2522966/examples/translation/data.py#L67-L68). Could you maybe change that code locally to use `with open(...)` instead of `lines = open(...)` and see if it helps? Otherwise, you'd need to find out what attribute of the `trainer` holds a reference to `TextIOWrapper` (try deleting suspicious attributes, then pickling, sorry that I don't have more specific advice).

NB: The whole translation notebook is very outdated and could need some love to be updated.

**Comment by drr3d** [comment]
Hi there,,

good point, then i try to look into the ProgresBar callback, and im able to reproduce those error by using this:
```
class ProgressBar():
    def __init__(self, batches_per_epoch):
        self.pbar = tqdm.tqdm(total=batches_per_epoch, leave=True)
        
    def start(self):
        with self.pbar as pbar:
            for i in range(100):
                sleep(0.1)
                pbar.update(10)
        
        self.pbar.close()

# exec pgbar
test_tqdm = ProgressBar(batches_per_epoch=1000)
test_tqdm.start()
```
then save it by:
```
# both of this dump will reproduce the error
pickle.dump(test_tqdm, open('test_tqdm', 'wb'))

with open('test_tqdm', 'rb') as f:
    pickle.dump(test_tqdm, f)
```
i dont know, but it may be something about tqdm module that causing error..

so for now i just left the ProgressBar callback, and change with PrintLog callback, thats enough to give me what i want..

thx for the help anyway..
Cheers :+1: 
keep up the good works :beers:

**Comment by BenjaminBossan** [comment]
Thanks a lot for investigating further. So it seems that `ProgressBar` is not pickleable. What you can also do is to leave the callback in and only remove it after training but before pickling (you have to pluck it from the `net.callback_` attribute).

I will open a bug ticket for `ProgressBar` and close this one.

> keep up the good works beers

Thanks, always nice to hear that :D
