### ISSUE TITLE
Question: LRScheduler error in 0.8.0 version

### ISSUE THREAD

**Issue by sakuranew** [skorch-dev/skorch#655]
in 0.8.0 version，
```
    def on_batch_end(self, net, training, **kwargs):
        if (
                training and
                hasattr(self.lr_scheduler_, 'batch_step') and
                callable(self.lr_scheduler_.batch_step)
        ):
            self.lr_scheduler_.batch_step(self.batch_idx_)
```
Normal LRScheduler  such as WarmRestartLR doesnt have batch_step function
but in master version,the code change and this is corrected,I just installed skorch by pip ,and find LRScheduler  doesn't word well.

**Comment by BenjaminBossan** [comment]
Hi, did I understand you correctly that the skorch version 0.8.0 on pip has a bug but the current version on master is good? In that case, I don't think we need to do anything, given that the bug seems to be fixed.

If you would like to install the master branch (or any other branch for that matter) of skorch via pip, please have a look at [this solution](https://stackoverflow.com/a/20101940).
