### ISSUE TITLE
Hyperparameter grid search pytorch

### ISSUE THREAD

**Issue by meghbhalerao** [skorch-dev/skorch#680]
Hi everyone,

I was wondering if there is a simple way of performing grid search for hyper-parameters in pytorch using your package? For example, assuming I have `3` possible values for parameter `a`, `3` for param `b` and `4` for param `c`, I have a total of `3 * 3 * 4 = 36` different combinations of hyper-parameters. Is there any way to do this efficiently? 

My motivation: Hyperparameters can drastically change the performance of a model. This seems like a very scary prospect since you can never know if your model is actually performing well or it is failing due to some hyper parameter combinations…
Please let me know if you could point me to somewhere in this repo to get an idea about this?
Thank you!

**Comment by BenjaminBossan** [comment]
Hi Megh, wie have a [section](https://github.com/skorch-dev/skorch#examples) in our README about grid search (scroll a bit down). A more elaborate example can be found in this [notebook](https://nbviewer.jupyter.org/github/skorch-dev/skorch/blob/master/notebooks/Basic_Usage.ipynb#Usage-with-sklearn-GridSearchCV).

If this solves the issue for you, feel free to close it, otherwise please post your follow up questions.

**Comment by meghbhalerao** [comment]
Hi @BenjaminBossan,
Thank you for your quick response. Will go through the link and follow up with questions if needed!
Thanks again!

**Comment by BenjaminBossan** [comment]
Since there was no follow-up for a week now, I assume that everything worked out fine. If not, please feel free to re-open the issue and report your problems.
