### ISSUE TITLE
Custom time series CV & RandomizedSearchCV not working (n_iter ignored)

### ISSUE THREAD

**Issue by dycw** [skorch-dev/skorch#684]
Hi all, I have a `NeuralNetRegressor` called which I'd like to tune. As it is for time series, and as I am new to the library, this is my best attempt at getting cross validation when fitting it manually:

```python

from typing import Any
from typing import Tuple

from sklearn.model_selection import TimeSeriesSplit
from skorch import NeuralNetRegressor
from skorch.callbacks import EarlyStopping
from skorch.dataset import CVSplit
from skorch.dataset import Dataset
from torch.optim import Adam
from torch.utils.data.dataset import Subset
from ... import SkorchNN


class TimeSeriesCVSplit(CVSplit):
    def __init__(self: TimeSeriesCVSplit, cv: int = 5) -> None:
        super().__init__(cv=cv)

    def __call__(
        self: TimeSeriesCVSplit,
        dataset: Dataset,
        y: Any = None,
        groups: Any = None,
    ) -> Tuple[Subset, Subset]:
        *_, (idx_train, idx_valid) = TimeSeriesSplit().split(dataset)
        return Subset(dataset, idx_train), Subset(dataset, idx_valid)

net = NeuralNetRegressor(  
    module=SkorchNN,
    module__input_size=num_assets,
    module__hidden_size=3,
    module__num_layers=2,
    module__output_size=num_assets,
    module__dropout=0.1,
    optimizer=Adam,
    optimizer__lr=1e-3,
    max_epochs=1000,
    train_split=TimeSeriesCVSplit(),
    callbacks=[
        EarlyStopping(patience=25),
    ]
)
```

That is, I want `TimeSeriesSplit` to split the time series into 6 (default) chunks for me and have training done on the first 5, and validation on the 6th. CV and the associated early stopping works. However, when it comes to `RandomizedSearchCV`, it just keeps going, ignoring `n_iter`...

```python
import scipy.stats
from numpy import arange
from sklearn.model_selection import RandomizedSearchCV

params = {
    'module__hidden_size': scipy.stats.randint(2, 100),
    'module__num_layers': scipy.stats.randint(2, 10),
    'module__dropout': scipy.stats.uniform(0., 1.),
    'optimizer__lr': 10.**-arange(9.),
    'max_epochs': scipy.stats.randint(100, 1000),
}
gs = RandomizedSearchCV(
    net,
    params,
    n_iter=5,
    scoring='neg_mean_squared_error',
    cv=TimeSeriesSplit(),
)
```

Help appreciated (and *love* the library!).

**Comment by BenjaminBossan** [comment]
> (and love the library!)

We're happy to hear that.

> However, when it comes to `RandomizedSearchCV`, it just keeps going, ignoring `n_iter`...

Could you please be more precise what you mean by that? Do you mean that the net keeps training even though it should stop because of early stopping? If so, that has nothing to do with `n_iter`. Or do you mean that `RandomizedSearchCV` keeps going, doing more than 5 searches?

Maybe you could also paste some outputs (increase the verbosity of `RandomizedSearchCV` for that).

Also, just to make sure that you understand what's happening during randomized search: sklearn will perform 5 `TimeSeriesSplit`s per iteration. For each of these splits, a new net is trained, and during this training, skorch performs yet another split using your `TimeSeriesCVSplit` (but only 1 split, not 5). Usually, when you use `RandomizedSearchCV`, you can turn off `train_split` (and set `verbose=0` on the net) since sklearn already performs the CV split, but in your case, you need the skorch CV split as well for early stopping.

Maybe that's exactly what you want, in which case leave it as is, I just want to make sure you're aware.

**Comment by BenjaminBossan** [comment]
@dycw Was your issue resolved? In case there is anything worth sharing, please post it in case other people run into the same problem in the future.
