### ISSUE TITLE
Rename CVSplit to ValidationSplit

### ISSUE THREAD

**Issue by timokau** [skorch-dev/skorch#752]
Hi! I was a bit surprised by the name of `CVSplit`. The name suggests that it is responsible for cross-validation, but the documentation [reveals](https://skorch.readthedocs.io/en/stable/user/dataset.html?highlight=CVSplit#cvsplit) that it only trains and validates on one split. That doesn't match my understanding of cross-validation. It could [technically](https://en.m.wikipedia.org/wiki/Cross-validation_(statistics)#Holdout_method) be seen as a special case of cross-validation, but I think it would be easier to understand if it was just called "validation".

This was previously discussed in #539. There are good reasons for the current behavior, and I am not proposing to change it. I think it would be an improvement to rename the class from `CVSplit` to `ValidationSplit` though. That name would likely lead to less surprises.

**Comment by BenjaminBossan** [comment]
Hi Timo, I agree that the CV part is used in a very loose sense. IIRC the main reason to name it this way was because it is compatible with sklearn cross validators. But I agree that the name can be confusing, I would actually go with `ValidSplit`. As they say, naming things is hard.

If you want to, you could provide a PR to implement this. It would require to deprecate the old `CVSplit`.

**Comment by TheCaffeineDev** [comment]
I can make PR changing `CVSplit` to `ValidSplit`. We need to put a deprecation warning also right?
