### ISSUE TITLE
Help test skorch support in explainerdashboard!

### ISSUE THREAD

**Issue by oegedijk** [skorch-dev/skorch#771]
Not sure if this is the appropriate place to put this, so if not: please remove.

I recently added skorch support to explainerdashboard: https://github.com/oegedijk/explainerdashboard

This should allow you to generate an interactive dashboard to interpret your model (mostly based on SHAP values), with just two lines of code. 

The sample `make_classification` and `make_regression` examples from the documentation seem to be working, but I'd really appreciate if someone could test it with their existing models and see if you run into any issues.

The constraint so far is that the input should consist of a single DataFrame X (`explainerdashboard` will extract the `np.array` and turn it into a `torch.tensor` in order to generate the SHAP values). 

Example code:

```sh
$ pip install explainerdashboard
```

```python
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression
from torch import nn

from skorch import NeuralNetRegressor

from explainerdashboard import RegressionExplainer, ExplainerDashboard

def get_skorch_regressor():
    X, y = make_regression(100, 5, n_informative=3, random_state=0)
    X = X.astype(np.float32)
    y = y / np.std(y)
    y = y.reshape(-1, 1).astype(np.float32)

    X_df = pd.DataFrame(X, columns=['col'+str(i) for i in range(X.shape[1])])

    class MyModule(nn.Module):
        def __init__(self, input_units=5, num_units=5, nonlin=nn.ReLU()):
            super(MyModule, self).__init__()

            self.dense0 = nn.Linear(input_units, num_units)
            self.nonlin = nonlin
            self.dense1 = nn.Linear(num_units, num_units)
            self.output = nn.Linear(num_units, 1)

        def forward(self, X, **kwargs):
            X = self.nonlin(self.dense0(X))
            X = self.nonlin(self.dense1(X))
            X = self.output(X)
            return X

    model = NeuralNetRegressor(
        MyModule,
        max_epochs=20,
        lr=0.2,
        iterator_train__shuffle=True,
    )

    model.fit(X_df.values, y)
    return model, X_df, y

model, X, y = get_skorch_regressor()
explainer = RegressionExplainer(model, X, y)
ExplainerDashboard(explainer).run()
```

**Comment by BenjaminBossan** [comment]
Thanks for reaching out. I didn't know about explainerdashboard, but have some familiarity with shap. Having a quick and convenient way of running your model through shap, getting partial dependence plots etc. is certainly useful.

Regarding your example, it looks good to me and should illustrate well how to use skorch. Since 2 of the features in `X` are just noise, if everything works, that should be reflected in the results.

A minor change I would propose is to just fit the model with `X` instead of `X_df.values` -- putting the data into a df only to extract it before passing it to `fit` looks like it doesn't add anything. It's a bit unfortunate that a df is necessary, but this is most likely a limitation of the underlying libraries.

**Comment by BenjaminBossan** [comment]
@oegedijk I assume that this resolves your initial question. If not, feel free to re-open the issue.
