### ISSUE TITLE
Can we use permutation importance from scikit learn using skorch model ?

### ISSUE THREAD

**Issue by sushmit86** [skorch-dev/skorch#799]
Can we use https://scikit-learn.org/stable/modules/permutation_importance.html using a skorch model?

**Comment by BenjaminBossan** [comment]
I took a look at the docs and code and don't see a reason why it shouldn't work.

As the docs state, the data should be tabular. Also, since skorch's nets don't implement a `score` method, be sure to provide the `scoring` argument to `permutation_importance`.

If you try it and it works, please let us know.

**Comment by sushmit86** [comment]
@BenjaminBossan  yes I was able to. I am amazed by the Skorch capabilities. Kudos to the dev team.

**Comment by BenjaminBossan** [comment]
That's good to hear. Thanks for your warm words. 

I'll close the issue since there are no more questions.
