### ISSUE TITLE
Slicing SliceDataset removes transform

### ISSUE THREAD

**Issue by gemeinl** [skorch-dev/skorch#816]
Hi,
If one slices a `SliceDataset` (as done automatically within scikit-learns `cross_validate`) which has a `transform` , the `transform` is not applied anymore. Below is a minimal working example to demonstrate this:
```
from skorch.helper import SliceDataset

class Dataset():
    def __getitem__(self, i):
        return i, None
    
    def __len__(self):
        return 10

ds = Dataset()
slice_ds = SliceDataset(ds, idx=0)
slice_ds.transform = lambda x: [x]
train_i = [0, 1]
# This is expected to be [0] but is 0
slice_ds[train_i][0]
```

Checking the return type in `__getitem__` and setting the `transform` when it is a `SliceDataset` could be a fix, although I do not know whether it brakes anything.
```
class CustomSliceDataset(SliceDataset):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def __getitem__(self, i):
        return_value = super().__getitem__(i)
        if isinstance(return_value, SliceDataset):
            return_value.transform = self.transform
        return return_value
```

**Comment by BenjaminBossan** [comment]
Thank you for reporting this bug.

I have a bit of a different solution. Could you please check if it solves your problem as well?

```python
class Dataset:
    def __init__(self):
        self.X = [1, 2, 3, 4]

    def __getitem__(self, i):
        return self.X[i], None
    
    def __len__(self):
        return len(self.X)


class MySliceDataset(SliceDataset):
    def transform(self, data):
        return [data]

    def __getitem__(self, i):
        if isinstance(i, (int, np.integer)):
            Xn = self.dataset[self.indices_[i]]
            Xi = self._select_item(Xn)
            return self.transform(Xi)

        if isinstance(i, slice):
            return type(self)(self.dataset, idx=self.idx, indices=self.indices_[i])  # <= change here

        if isinstance(i, np.ndarray):
            if i.ndim != 1:
                raise IndexError("SliceDataset only supports slicing with 1 "
                                 "dimensional arrays, got {} dimensions instead."
                                 "".format(i.ndim))
            if i.dtype == np.bool:
                i = np.flatnonzero(i)

        return type(self)(self.dataset, idx=self.idx, indices=self.indices_[i])  # <= change here

ds = Dataset()
slice_ds = MySliceDataset(ds, idx=0)
train_i = [0, 1]
slice_ds[train_i][0]  # returns [1]
```

I believe the problem is that `__getitem__` returns `SliceDataset` instances, even if it is not bound to `SliceDataset` but instead to a subclass. By replacing `SliceDataset` with `type(self)`, this is fixed above.

If this suggestion solves your problem, I would prefer it instead of attaching new methods on the fly as in your example.

**Comment by gemeinl** [comment]
I think I did not make my point clear enough. I do not want to write a custom class but to use `skorch.helper.SliceDataset`.
The class does not accept a `transform` on initialization but applies one when `__getitem__` is called (https://github.com/skorch-dev/skorch/blob/master/skorch/helper.py#L233). By default the `transform` is the identity (https://github.com/skorch-dev/skorch/blob/master/skorch/helper.py#L206-L215) but the documentation says it can be used for additional transformations (https://skorch.readthedocs.io/en/stable/helper.html#skorch.helper.SliceDataset.transform). 
When the dataset is now sliced, another instance of `SliceDataset` is created which does not adopt the `transform` (https://github.com/skorch-dev/skorch/blob/master/skorch/helper.py#L235-L236). Your proposed solution with `type(self)()` instead of `SliceDataset()` also does not solve this.

**Comment by BenjaminBossan** [comment]
I see your point now. As you mentioned, `SliceDataset` should call `transform`, which by default does nothing. In order for it to do something, the intended way is to subclass `SliceDataset` (as in my example) and override the `transform` method. With the current implementation, since `__getitem__` hard-codes `SliceDataset` as the return type, this new `transform` method is not called. With the proposed solution, it should be called.

The way of overriding `transform` from your original example is not the intended way. I'm actually not sure what happens but I don't think that replacing the attribute properly binds the new function as an instance method. Therefore, my proposed solution might not work there, but it should work when subclassing.
