### ISSUE TITLE
Support Pytorch DDP

### ISSUE THREAD

**Issue by YUHUINI1995** [skorch-dev/skorch#933]
Is it possible for skorch to integrate with pytorch DDP just like [pytorch_lightning](https://github.com/Lightning-AI/lightning/tree/master/src/pytorch_lightning)?

**Comment by BenjaminBossan** [comment]
I haven't tried it, so I cannot answer your question. skorch does not have anything that would automatically turn on DDP for you, if you want to try it, you would need to go through the steps yourself. If skorch is in the way, I would be happy to help and make adjustments for skorch to get out of the way.

If you need more automation, it should be possible to run skorch together with [accelerate](https://huggingface.co/docs/accelerate/index). You need to use accelerate to [launch the training script](https://huggingface.co/docs/accelerate/usage_guides/fsdp) but instead of running `accelerator.prepare`, use the skorch [`AccelerateMixin`](https://skorch.readthedocs.io/en/stable/user/huggingface.html#accelerate).

**Comment by BenjaminBossan** [comment]
@YUHUINI1995 Did you have any success?

**Comment by BenjaminBossan** [comment]
In the [latest release](https://github.com/skorch-dev/skorch/releases/tag/v0.13.0), we improved support for DDP via `accelerate`, [here](https://github.com/skorch-dev/skorch/tree/master/examples/accelerate-multigpu) are some pointers.

I hope this solves the issue. If you run into trouble, feel free to re-open.
