### ISSUE TITLE
Can't convert data type to numpy array

### ISSUE THREAD

**Issue by gummz** [skorch-dev/skorch#937]
I'm building a CNN using Skorch and the Caltech101 dataset.

[Reproducing Colab notebook](https://drive.google.com/file/d/1NZ_SqxUk8_s6diJMFrOnPvYHgcd5zpPy/view?usp=sharing)

The error: if you remove the underscore `_` from `y_`, so to `y`, the error "Can't convert data type to numpy array" occurs. However, `y` is just a tuple of integers.

If you instead remove the underscore from `X_`, then the error "X and y have inconsistent lengths" occurs. But as the print statements show, the arrays do have consistent lengths.

I've gotten around these errors by applying a `torch.stack` to X, and casting `y` to `np.int64`.

**Comment by BenjaminBossan** [comment]
Thanks for reporting. I'm not quite sure I understand your problem, is it that you would expect `net.fit(X, y)` to work?

The issue is that in your example, `X` is a tuple, with each element being an image of shape 3 x 128 x 128. When `X` is a tuple, skorch will make the assumption that each element of that tuple consists of a number of independent samples, so here, it thinks there are 3 samples. Obviously, this gives an error because in reality there are 870 samples, which corresponds to the length of `y`.

As you have figured out yourself, using `torch.stack` to create a tensor with size 870 x 3 x 128 x 128 solved the issue.

Maybe you would like to know why skorch behaves this way if `X` is a tuple? The reason is that we wanted to cover the use cases where people have multiple `X`s that together present the input. Then they can pass those `X`s as a tuple or list and it will work. Here is an example:

```python
# 2 inputs, X0 and X1
X0 = np.random.random((100, 10)).astype(np.float32)
X1 = np.random.random((100, 20)).astype(np.float32)
X = (X0, X1)  # <= passing X0 and X1 together as a tuple
y = np.random.randint(0, 2, size=100)

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin0 = nn.Linear(10, 8)
        self.lin1 = nn.Linear(20, 8)
        self.out = nn.Linear(16, 2)
        self.sm = nn.Softmax(dim=-1)
        
    def forward(self, X):
        X0, X1 = X
        X0, X1 = self.lin0(X0), self.lin1(X1)
        X01 = torch.hstack((X0, X1))
        out = self.out(nn.functional.relu(X01))
        return self.sm(out)

net = skorch.NeuralNetClassifier(MyModule)
net.fit(X, y)
```

**Comment by BenjaminBossan** [comment]
@gummz Any updates, did this explain the issue?
